import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import 'app/ui/styles/globals.css';
const inter = Noto_Sans({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    template: '%s | OWL',
    default: 'OWL Top',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
